### ISSUE TITLE
Strange flight behavior during flight today

### ISSUE THREAD

**Issue by learnin2fly** [OpenSolo/OpenSolo#11]
Hello, I am new to the 3dr and open solo, so I apologize in advance if this is not the right place to ask for help/explanation.

Today I went to the park to fly my solo that I recently got (and it has been updated to open solo 4 successfully, as well as the controller, per the instructions). While flying, a park ranger pulled up so I hit the return to home button so I could talk with him and we were both watching it return home but it got about 50 feet from us, stopped, kind of drifted to the south for a second, then the engines turned off and the solo started to free fall back to the north for about 2 seconds before auto correcting. That's when I manually took over the landing and the solo faught me landing it and stopping the motors.  It kept trying to gain altitude and not land.... all of this was recorded by my GoPro also, if the video would be helpful in any way.  I have no idea what this was all about but now I'm hesitant to fly it again because of this ... Does anyone have any explanation of what occured by chance? Thank you, and if this is not where this need to be discussed, could you please refer me to the proper place so I may ask there? 

I appreciate all the work that has gone into keeping these drones going. A vast amount of information has been entered I to my brain all at once when it comes to these drones a now that I have one, and although a lot of it is like reading a foreign language to me still, I am hopeful to become more knowledgeable about these drones so that I can interact with others intelligently, for now though, I am truly sorry for my ignorance on terms, etc , so please explain any responses so that I can understand them if you don't mind. Thank you

Learnin2fly
(Brittany)

**Comment by Pedals2Paddles** [comment]
Not really following what you describe since you say the motors turned off and started free falling north.  The video or log files would be helpful.  But I would  venture a guess the GPS signal was lost and came back based on what I think you're describing.

**Comment by davidbuzz** [comment]
sounds like an ardupilot configuratin issue, kinda sounds lik it was in the wrong mode or trying to rtl or failsafe, but without logs ththere's nothing we can do here.    please use ardupilot forums for this sort of thing in the future.
