### ISSUE TITLE
Drone bricked from OpenSolo update using SidePilot - also solo CLI not working 

### ISSUE THREAD

**Issue by Corzine82** [OpenSolo/OpenSolo#12]
Hi guys,
I think I got myself a bit in over my head, any help greatly appreciated. 

I recently brought out my 3DR solo drone yesterday to fly since the weather is good and went to login to my 3DR solo app and realized its no longer supported.  

So I downloaded SidePilot on my iPhone 12 Pro Max and after testing the drone to make sure it worked I updated the controller and drone to OpenSolo 4, the controller updated and the drone started rebooting by itself acting like it was also reloaded.  I turned them both off now the controller just says waiting for solo and won't connect.

Also, I have a MacBook pro and when I tried to install the CLI tool for the solo I kept getting the following error: "ERROR: For req: solo-cli==1.2.0. Invalid script entry point: <ExportEntry solo = soloutils.__main__:None []> - A callable suffix is required. Cf https://packaging.python.org/specifications/entry-points/#use-for-scripts for more information."

**Comment by lmfranco** [comment]
Hi Corzine82, did you find a solution? I´m facing the same issue. Thank you.

**Comment by Corzine82** [comment]
> Hi Corzine82, did you find a solution? I´m facing the same issue. Thank you.

Hey, yeah I did figure it out but it’s been so long I can’t walk you through the steps.  What I think I did was try to reset everything back to factory with the new software drone and controller and be patient with it… it eventually loaded up the new silo pilot software.

**Comment by SpencerFreeman** [comment]
> 

Were you able to fix the CLI install issue? I have that as well on Windows

Thanks!

**Comment by kengregson** [comment]
The CLI issue is addressed in https://github.com/3drobotics/solo-cli/issues/59, duplicated here for OpenSolo:

Also ran into this using Ubuntu 20.04 and solved it by cloning repo locally, changing line in setup.py from:
```
'solo = soloutils.__main__'
```
to:
```
'solo = soloutils:__main__'
```
and installing from local directory with:
>sudo pip install .

Haven't tested anything yet, YMMV.
