### ISSUE TITLE
After update to Solo 4, controller do not find solo

### ISSUE THREAD

**Issue by lmfranco** [OpenSolo/OpenSolo#15]
I have followed the instruction to update to Solo 4, but after update the drone and controller were restarted and controller is only in state "waiting for solo". Please, I need a help if someone have already faced this kind of issue. Thank you.

**Comment by sparkplug23** [comment]
Did you repair it? (Hold solo pair pin for 3 seconds then follow controller instructions)

**Comment by kielerrr** [comment]
I am having this issue as well. Holding fly and power does not put it into update mode either. leds are green red and two yellow which after a time turn blue. Any ideas?

**Comment by davidbuzz** [comment]
there are plenty of instructions on the internet about what to do if the process doesn;t work... the short answer is repeat the process from the beginning,
