### ISSUE TITLE
OpenSolo 4.0.0  - RC7 does not respond/change with long/short press of the Pause button

### ISSUE THREAD

**Issue by AndKe** [OpenSolo/OpenSolo#18]
The Controllers haptic feedback confirms the input, but monitoring RC_CHANNELS.chan7 does nothing.
AP4.0.3 
[params.zip](https://github.com/OpenSolo/OpenSolo/files/7153789/params.zip)

What could be a possible reason for this ?

**Comment by davidbuzz** [comment]
asking support questions in the issues is the wrong place to do it.  please use one of the many user-forums for ArduPilot and/or OpenSolo.  If you believe this is a bug in the code, please re-open with enough evidence that its repeatable for other users.

**Comment by AndKe** [comment]
@davidbuzz   I agree,  - I also tried such forum, but this is not a feature that very many use, so it is less likely to get any reply.
