### ISSUE TITLE
Trying to update the firmware. 

### ISSUE THREAD

**Issue by Breadeder12** [OpenSolo/OpenSolo#19]
When trying to update the firmware through SSH ( following [this ](https://github.com/OpenSolo/OpenSolo/wiki/Install-via-SSH) guide ) I receive this error : shell-init: error retrieving current directory: getcwd: cannot access parent directories: Success md5sum: *solo*.tar.gz.md5: No such file or directory md5 error when this command is run: sololink_config --update-apply sololink --reset . If anyone could help with this I would be greatly appreciated - I am struggling quite a bit to get these working. Thanks!

[
![image](https://user-images.githubusercontent.com/90717349/133306118-7d1b34a7-982e-462e-8852-7bd641a4dfce.png)
](url)

**Comment by davidbuzz** [comment]
"Copy 3dr-solo.tar.gz and 3dr-solo.tar.gz.md5 to the /log/updates directory on the copter.
...
Copy 3dr-controller.tar.gz and 3dr-controller.tar.gz.md5 to the /log/updates directory on the controller."
...excerpt from that wiki page, u did not follow instructions correctly.
