### ISSUE TITLE
shotmanager.py: str_BattHealth not declared as instance variable

### ISSUE THREAD

**Issue by mtbsteve** [OpenSolo/OpenSolo#2]
In routine `def checkBatteryHealth(self)` the variable `str_BattHealth` should be instanciated as `self.str_BattHealth` as it is already declared in the `def __init__` section of the shotmanager class.
Currently, python throws an exception at startup.

**Comment by Pedals2Paddles** [comment]
oops.  Thanks Steve.  I saw that in the stderr log a while ago and forgot all about it.
