### ISSUE TITLE
Something strange with IMX6 MAVLink  ?

### ISSUE THREAD

**Issue by AndKe** [OpenSolo/OpenSolo#22]
SoloLink/OpenSolo 4.0.0
ArduPilot can be configured with serial protocol=1 or 2 (MAVLink 1.x or 2.0) - it has no effect on this issue.

QGroundcontrol works regardless (I assume it got some internal version detection)

AP2 and MAVProxy will receive data, but fail to issue any commands, or request mission/parameters.
If MAVProxy is started with parameter --mav10 (Forced to MAVLink1.0) , then it will work fully.

Interestingly - the MAVLink version force/detection issue happens only when communicating over IMX6/SoloLink.  - not to directly connected to some serial port.

@Pedals2Paddles any thoughts? - what/where is the issue?  - it there something wrong with the MAVLink version inside OpenSolo?

**Comment by davidbuzz** [comment]
open solo uses a very old mavlink verson for parts of the codebase.

**Comment by AndKe** [comment]
@Pedals2Paddles - I hope you can enlighten us.
