### ISSUE TITLE
GitDesktop Failing to clone 

### ISSUE THREAD

**Issue by Decryptortuning** [OpenSolo/OpenSolo#23]
If I attempt to clone this repo directly, it attempts to pull in all these old outdated 'modules'. It is failing in this one in particular.
https://github.com/OpenSolo/imx6-linux/tree/c823ff8fe0516cfc75fa9643e2463e7b5b341b31

Do we need to tweak some git settings to keep these modules out during a clone? Doing a direct download of this repo DOES NOT include the modules.

**Comment by Decryptortuning** [comment]
![image](https://user-images.githubusercontent.com/19156562/167194955-bd0f7563-4073-4861-a2ef-198cc171e8aa.png)

**Comment by Decryptortuning** [comment]
I dug a bit deeper and tried to clone the im6-linux repo directly.
![image](https://user-images.githubusercontent.com/19156562/167196454-9d8181bf-c8af-4084-9295-da6ebd4eaa64.png)

**Comment by kevinmehall** [comment]
The Linux kernel source tree contains filenames like `aux.c` that aren't allowed on Windows. See https://github.com/raspberrypi/linux/issues/1254 for details.

If you're trying to build the kernel, you need to use a Linux system for that to work anyway. If you're not, then you don't need that submodule and can just skip it. Not sure how you configure your Git GUI not to clone submodules. `git` CLI doesn't recurse into submodules by default.

**Comment by Decryptortuning** [comment]
This issue is solved by using git command line
