### ISSUE TITLE
Build issues V2.0

### ISSUE THREAD

**Issue by Decryptortuning** [OpenSolo/OpenSolo#25]
@davidbuzz Your the man! Thanks for the last round of fixes.
Current issues:
1. Tup is broken on the same line 278 of assetgen.py for me. Thats on a clean clone and re-setup of it all.
![image](https://user-images.githubusercontent.com/19156562/167663016-87486f9b-b3be-43be-bba2-202960c1ca5c.png)
![image](https://user-images.githubusercontent.com/19156562/167663045-489fc2ef-7a59-4703-83c9-295e7d081939.png)
![image](https://user-images.githubusercontent.com/19156562/167663076-7df5a2a8-d696-4163-8e47-cfe53bec56fb.png)

2. The build script did get further. Currently, it is yelling about an xpg echo. ***THIS IS FIXED BY UNIX EOL FEED and deleting new line after xpg_echo.**

 Cloning into '/solo-build/sources/meta-fsl-bsp-release'...
Already on 'dora_3.10.17-1.0.0_GA'
Your branch is up to date with 'origin/dora_3.10.17-1.0.0_GA'.
: invalid shell option name: shopt: xpg_echo
./setup-environment: line 3: $'\r': command not found
./setup-environment: line 24: $'\r': command not found
./setup-environment: line 28: $'\r': command not found
./setup-environment: line 29: syntax error near unexpected token `$'\r''
'/setup-environment: line 29: `usage()
Machine export error.

![image](https://user-images.githubusercontent.com/19156562/167663593-54c6d3df-165b-4b1d-a607-145fe571b238.png)

3. sources/poky/meta/recipes-core/update-rc.d/update-rc.d_0.7.bb 
13: SRC_URI = "git://github.com/philb/update-rc.d.git \
 This file 'update-rc.d_0.7.bb' in the VM needs permanent updating for git to https.

**Comment by davidbuzz** [comment]
sounds like these issues are from cloning the repo on a windows box , as i can't replicate the issue here on a linux box. if you wnt to fix it, and do a pr you are welcome to, but i won't be attempting to fix this, as i can't replicate it here, on linux host.
