### ISSUE TITLE
Sitescan gimbal and Sony R10C support 

### ISSUE THREAD

**Issue by csanchez131** [OpenSolo/OpenSolo#27]
Hi, I have a 3DR Solo with the gimbal and Sony camera R10C that was use with sitescan app but won’t get recognized with solex, tower or any app that allows you to control the solo. Any ideas?

**Comment by davidbuzz** [comment]
Nothing about sitescan was opensourced

**Comment by csanchez131** [comment]
Hi David, thanks to the reply. Another user mentioned a library that provides the functionality for the gimbal and Sony camera here. Is there a way to load this library into the drone or has to be in the open solo image https://github.com/3drobotics/ardupilot-solo/tree/master/libraries/AP_Mount

**Comment by csanchez131** [comment]
Hi, does anyone know how to load this library https://github.com/3drobotics/ardupilot-solo/tree/master/libraries/AP_Mount into the drone?
