### ISSUE TITLE
Light LED

### ISSUE THREAD

**Issue by NatalinoIT** [OpenSolo/OpenSolo#4]
changing light color on sole do not save, after restart solo leds are again 2 yellow on the back and one green and one red on the front

**Comment by Pedals2Paddles** [comment]
Are you changing them using the LED control python script that Hugh Eaves made? If so, that is expected behavior. The LED override with scripts is temporary on-demand. It is not a permanent change.

**Comment by NatalinoIT** [comment]
after i install open solo 4 i have 2 LED yellow and in the front one green one red, i change it the color with solex but they not save this

**Comment by Pedals2Paddles** [comment]
Those changes are temporary and do not stick through a reboot.

**Comment by NatalinoIT** [comment]
ok thank fot this information, 
but why is on open solo4 2 yellow one green and one red?
is this changeble?

**Comment by NatalinoIT** [comment]
like the original front green back red

thanks in advance
