### ISSUE TITLE
git.freescale.com/imx/meta-fsl-bsp-release not available

### ISSUE THREAD

**Issue by professorpip** [OpenSolo/OpenSolo#5]
As per https://3drpilots.com/threads/git-freescale-com.15511/post-149307 the freescale git repository needs to be changed.

I managed to get it to build manually by adjusting a the sources in /solo-builder/source_sync.sh to replace the git clone from the git.freescale.com repo to:
git clone --branch nxp/dora_3.10.17-1.0.0_GA https://source.codeaurora.org/external/imx/meta-fsl-bsp-release/ $source_dir/meta-fsl-bsp-release

But am not 100% sure this is the best alternative to the original repo.

**Comment by davidbuzz** [comment]
fixed some time back by using https://github.com/opensolo/meta-fsl-bsp-release instead
