### ISSUE TITLE
can't use geofence in Mission Planner

### ISSUE THREAD

**Issue by looninho** [OpenSolo/OpenSolo#8]
Hi,
I was using geofence with MP and if I remember well I was using AC 3.5 on Solo. But after upgrading to opensolo 4 thus AC 4.0.1 it doesn't work, I can't write geofence to Solo the command GEOFENCE_POLYGON_INCLUSION seems didn't recognize by Solo.
Can I upgrade Solo GreenCube to AC 4.0.3 like Arducopter?

**Comment by davidbuzz** [comment]
yes.

**Comment by looninho** [comment]
thank you @davidbuzz
